### PR TITLE
Added album art

### PR DESCRIPTION
**Pull request by joostlek**

### CODE REVIEW

**Comment by wrxck** [comment]
Are you sure line 78 is the correct API?

**Comment by wrxck** [comment]
I'm pretty sure it's something like configuration.apis.itunes.album_artwork but I can't check because my college has automatically blocked my configuration.lua file for containing the word ass xD

**Comment by joostlek** [comment]
@matthewhesketh I literally copied the iTunes art plugin

**Comment by wrxck** [comment]
Oh right my bad xD

**Comment by wrxck** [comment]
Lemme just test it and if it works I'll commit

**Comment by joostlek** [comment]
@matthewhesketh But I'm not sure if the input is correct

**Comment by wrxck** [comment]
What do you mean?

**Pull request merged**
