### PR TITLE
Fixed a bug

### PR DESCRIPTION
**Pull request by joostlek**
<3

### CODE REVIEW

**Comment by aRandomStranger** [comment]
@joostlek 🙊

**Comment by TheZeus121** [comment]
@aRandomStranger 😂😂😂

**Review by wrxck — APPROVED** [review]
Thanks, I'm a fucking idiot

**Comment by wrxck** [comment]
I really am a fucking idiot

**Comment by TheZeus121** [comment]
@matthewhesketh It's ok Matt

**Comment by wrxck** [comment]
xD

**Pull request merged**
