### PR TITLE
docker-compose setup

### PR DESCRIPTION
**Pull request by italomaia**
Adding docker compose-setup for mattata; now, using it is as easy as calling **docker-compose up**

### CODE REVIEW

**Comment by TheWildBear** [comment]
Thank you for makeing the **Dockerfile**!
I was preparing the same stuff, but didn't have the time to finish it, before you came around. The last line in every file is missing.

Unfortunatly I can't test the code, as I am in holiday, but i believe you have to symlink `lua `to `lua5.3` aswell... [https://bugs.launchpad.net/ubuntu/+source/lua5.3/+bug/1707212](url)

I also suggest using the `redis:alpine` cause of security! And also maybe base the whole system on [`alpine`](https://hub.docker.com/_/alpine/). Btw. alpine is about 5 mb large. I was thinking on how to implement that. That would boost the securtiy and should also help speeding up the bot.

**Comment by italomaia** [comment]
Changed broker image to alpine and added new line at the end of files. What about adding an .editorconfig file?
About the symlink, I had no issues without it. I can add one if you want it.
About alpine, it was simple to make redis use it as base, but for the bot, I believe it would take much more work. A lot of packages would have to be compiled. 
What about having it as is and registering a issue to parse the Dockerfile to alpine? For what I read, alpine big advantage is being small. If only for security, debian is probably a good choice too.

**Comment by TheWildBear** [comment]
Adding an .editorconfig would be very good, and should really be done to get some more consistency. Oh okay good, if lua works without the symlink aswell than we can get rid of that stuff in the installer aswell. If so many things have to get added than we should stick to debian.

**Comment by imaia** [comment]
I bumped on most of #43 fixes along the way. Nice PR

**Comment by wrxck** [comment]
This is really cool, thanks!

**Pull request merged**
