### PR TITLE
I thought I already fixed  this

### PR DESCRIPTION
**Pull request by joostlek**

### CODE REVIEW

**Comment by wrxck** [comment]
This isn't the issue, the issue is the plugin is still displaying album artwork for Unknown songs, so we need something that returns the message without album artwork if the artist/song is Unknown.

**Comment by joostlek** [comment]
@matthewhesketh Yeah, but it will always return anything, so you can't really fix it i think

**Comment by wrxck** [comment]
How about changing it to something like:

```
if jdat.results[1].artworkUrl100 then
        if string.match(output, 'Unknown') then
                functions.send_reply(msg, output)
                return
        else
                local artworkUrl100 = jdat.results[1].artworkUrl100:gsub('/100x100bb.jpg', '/10000x10000bb.jpg')
                telegram_api.sendChatAction{ chat_id = msg.chat.id, action = 'upload_photo' }
                functions.send_photo(msg.chat.id, functions.download_to_file(artworkUrl100), output, msg.message_id)
                return
        end
else
```

etc.

**Comment by wrxck** [comment]
(Updated comment)

**Comment by aRandomStranger** [comment]
@matthewhesketh Looks fine.

**Comment by wrxck** [comment]
I would do it myself but I'm away from home at this point in time so I'll refrain from doing it.

**Comment by wrxck** [comment]
Oh hi Florian xD

**Comment by aRandomStranger** [comment]
@matthewhesketh Upon request I could do that for you.

**Comment by joostlek** [comment]
Isn't it iTunes that is giving Unkown instead of last.fm?

**Comment by wrxck** [comment]
iTunes is returning the Unknown album artwork, if the song is Unknown I just want a text reply.

**Comment by wrxck** [comment]
The unknown reply is typically returned when a user sends `/np` to mattata and hasn't played anything.

**Comment by joostlek** [comment]
Does last.fm give unified unkown strings back, or is it like

Unkown
Unkown Artist
unkown 
etc

**Comment by wrxck** [comment]
Unified

**Comment by wrxck** [comment]
It's always Unknown - Unknown

**Comment by joostlek** [comment]
I'll check it out when i'm done with my english stuff

**Comment by wrxck** [comment]
Which is pretty useful lol

**Comment by wrxck** [comment]
Alright cheers dude

**Comment by aRandomStranger** [comment]
@joostlek It returns Unknown, random messages wouldn't make sense. 

www.last.fm/api/show/track.getInfo

**Comment by joostlek** [comment]
There are more things that doesnt make sense

**Comment by wrxck** [comment]
WELP. This is an old issue, which was resolved a while ago (iirc). I'm gonna go ahead and close it now. I'm pretty sure the only reason I didn't close it sooner was to try and sabotage @joostlek's chances of getting 4 PRs for Hacktoberfest lmaoooo

**Pull request closed without merging**
